# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #  apt-get update
  #  apt-get install -y apache2
  # SHELL

  # Disabling mounting of the /vagrant directory
  # Comment this out to allow the shared folder
  config.vm.synced_folder ".", "/vagrant", disabled: true


    # config.vm.provision :file, source: "./nomad", destination: "/tmp"
    # config.vm.provision :file, source: "./consul", destination: "/tmp"

    # config.vm.provision :shell, path: "bootstrap-consulnomad.sh"
    # config.vm.provision :shell, path: "bootstrap-dotnetcore214.sh"
    # config.vm.network :forwarded_port, guest: 80, host: 8080
    
    # config.vm.provision "docker"

    CONSUL_VERSION = ENV['CONSUL_VERSION'] || "1.0.6"
    NOMAD_VERSION = ENV['NOMAD_VERSION'] || "0.7.1"

    config.vm.network "public_network", auto_config: false

    # Servers
    1.upto(1) do |i|
        vmName = "master-#{i}"
        vmIP = "192.68.50.1#{i}"
        config.vm.define vmName do |server|
            #server.vm.box = "ubuntu/trusty64"
            server.vm.hostname = vmName
            server.vm.network "private_network", ip: vmIP
            server.vm.provision :file, source: "./master", destination: "/tmp/files"
            server.vm.provision :shell, path: "./scripts/consulnomad.sh", env: {
                # Specify Consul and Nomad versions
                'CONSUL_VERSION' => CONSUL_VERSION,
                'NOMAD_VERSION' => NOMAD_VERSION,
            }
            server.vm.provision :shell, path: "./scripts/cluster.sh"
        end
    end

    # Clients
    1.upto(1) do |i|
        vmName = "slave-#{i}"
        vmIP = "192.68.60.1#{i}"
        config.vm.define vmName do |server|
            #server.vm.box = "ubuntu/trusty64"
            server.vm.hostname = vmName
            server.vm.network "private_network", ip: vmIP
            server.vm.provision :file, source: "./slave", destination: "/tmp/files"
            server.vm.provision :shell, path: "./scripts/consulnomad.sh", env: {
                # Specify Consul and Nomad versions
                'CONSUL_VERSION' => CONSUL_VERSION,
                'NOMAD_VERSION' => NOMAD_VERSION,
            }
            server.vm.provision :shell, path: "./scripts/cluster.sh"
        end
    end

    # Increase memory for Virtualbox
    config.vm.provider "virtualbox" do |vb|
        vb.box = "ubuntu/trusty64"
        vb.memory = "1024"
    end

    # Increase memory for Hyper-V
    config.vm.provider "hyperv" do |hb|
        hb.box = "bento/ubuntu-14.04"
        hb.memory = "1024"
    end
end
